apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nithya-resume
  name: nithya-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
    nodePort: 30000
  selector:
    app: nithya-resume
  type: NodePort
status:
  loadBalancer: {}
